# Generated by Django 5.1.4 on 2024-12-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('selfie', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
    ]
